In [22]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA

In [7]:
import pandas as pd
import numpy as np

In [5]:
scaler = MinMaxScaler()

>>> from sklearn.preprocessing import MinMaxScaler
>>> data = [[-1, 2], [-0.5, 6], [0, 10], [1, 18]]
>>> scaler = MinMaxScaler()
>>> print(scaler.fit(data))
MinMaxScaler()
>>> print(scaler.data_max_)
[ 1. 18.]
>>> print(scaler.transform(data))
[[0.   0.  ]
 [0.25 0.25]
 [0.5  0.5 ]
 [1.   1.  ]]
>>> print(scaler.transform([[2, 2]]))
[[1.5 0. ]]

In [44]:
day = pd.read_csv('day.csv')

In [60]:
Q = pd.read_csv('Q_data.csv')

In [14]:
day.head()

,Date,Close_BP,Volume_BP,Close_XOM,Volume_XOM,Close_crude_oil,Volume_crude_oil,Close_DSI
0,2009-12-31,57.970001,1517600,68.190002,18852300,79.360001,120372,21.355000
1,2010-01-04,59.150002,3956100,69.150002,27809100,81.510002,263542,21.639999
2,2010-01-05,59.570000,4109600,69.419998,30174700,81.769997,258887,21.674999
3,2010-01-06,59.880001,6227900,70.019997,35044700,83.180000,370059,21.660000
4,2010-01-07,59.860001,4431300,69.800003,27192100,82.660004,246632,21.735001

In [45]:
scaler.fit(day.iloc[:,1:])

MinMaxScaler()

In [46]:
pd.DataFrame(scaler.transform(day.iloc[:,1:])).describe()

,0,1,2,3,4,5,6
count,2870.000000,2870.000000,2870.000000,2870.000000,2870.000000,2870.000000,2870.000000
mean,0.507174,0.032052,0.637104,0.111530,0.704542,0.163392,0.329481
std,0.168876,0.051330,0.203716,0.082716,0.150499,0.097613,0.231608
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.423292,0.013955,0.548677,0.055827,0.577544,0.090424,0.104515
50%,0.539751,0.021276,0.689154,0.086466,0.674551,0.137868,0.300276
75%,0.604755,0.034660,0.767997,0.140830,0.853837,0.225933,0.490260
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [47]:
day = pd.DataFrame(scaler.transform(day.iloc[:,1:]))

In [57]:
day[[2]]

             2
0     0.503771
1     0.516934
2     0.520636
3     0.528863
4     0.525847
...        ...
2865  0.449883
2866  0.453448
2867  0.455368
2868  0.432744
2869  0.427396

[2870 rows x 1 columns]

In [58]:
X = day[[0,1,3,4,5,6]]
Y = day[[2]]

In [59]:
pca = PCA(n_components=6)
pca.fit_transform(X)
print(pca.explained_variance_ratio_)

[0.66234716 0.14585519 0.09411273 0.05180045 0.03047687 0.01540759]

In [61]:
Q_scaler = MinMaxScaler()

In [62]:
Q_scale= Q_scaler.fit_transform(Q.iloc[:,1:])

In [63]:
Q_scale.shape

(29, 16)

In [72]:
Q

,Q,Close_x,Dividends,부채총계,자산총계,순이익,매출액,부채비율,자기자본이익률,매출순이익률,esg,시가총액,경상수지,성장률,실업률,Volume,interest
0,2013-1Q,88.250000,0.57,166562,339639,9500,108357,0.490409,0.027971,0.087673,26.600,373.650500,-72772.0,0.9,7.733333,1.272926e+07,0.28260
1,2013-2Q,91.029999,0.63,170027,341615,6860,106666,0.497715,0.020081,0.064313,36.075,385.421015,-92185.0,0.1,7.533333,1.353616e+07,0.27310
2,2013-3Q,90.720001,0.63,172086,347564,7870,112372,0.495120,0.022643,0.070035,45.550,384.108485,-103363.0,0.8,7.233333,1.169397e+07,0.24885
3,2013-4Q,91.959999,0.63,166313,346808,8350,110860,0.479554,0.024077,0.075320,55.025,389.358636,-68533.0,0.8,6.933333,1.261614e+07,0.24610
4,2014-1Q,89.800003,0.63,170142,353033,9100,106325,0.481944,0.025777,0.085587,64.500,380.213213,-71354.0,-0.3,6.666667,1.257954e+07,0.23060
5,2014-2Q,101.949997,0.69,170455,358586,8780,111208,0.475353,0.024485,0.078951,69.650,431.656287,-91906.0,1.4,6.200000,9.835862e+06,0.23070
6,2014-3Q,98.730003,0.69,165269,352764,8070,107130,0.468497,0.022876,0.075329,74.800,418.022834,-106988.0,1.2,6.066667,9.524620e+06,0.23510
7,2014-4Q,96.589996,0.69,168429,349493,6570,87276,0.481924,0.018799,0.075278,79.950,408.962044,-97564.0,0.6,5.700000,1.485762e+07,0.25560
8,2015-1Q,91.500000,0.69,165515,342961,4940,67618,0.482606,0.014404,0.073057,85.100,387.411000,-84583.0,0.9,5.533333,1.530090e+07,0.27080
9,2015-2Q,86.779999,0.73,169262,348260,4190,74113,0.486022,0.012031,0.056535,100.275,367.426515,-102922.0,0.7,5.433333,1.092849e+07,0.28320
10,2015-3Q,77.489998,0.73,163823,340662,4240,67344,0.480896,0.012446,0.062960,115.450,328.092651,-123022.0,0.4,5.100000,1.532923e+07,0.32500
11,2015-4Q,81.949997,0.73,159948,336758,2780,40173,0.474964,0.008255,0.069201,130.625,346.976287,-96829.0,0.2,5.033333,1.478448e+07,0.61270
12,2016-1Q,80.080002,0.73,164291,342789,1810,48707,0.479277,0.005280,0.037161,145.800,339.058728,-91554.0,0.6,4.900000,1.778567e+07,0.62860
13,2016-2Q,88.809998,0.75,165598,342473,1700,57694,0.483536,0.004964,0.029466,168.825,376.021530,-101344.0,0.3,4.933333,1.081912e+07,0.65410
14,2016-3Q,86.410004,0.75,162376,339386,2650,58677,0.478440,0.007808,0.045162,191.850,365.859956,-113399.0,0.5,4.900000,1.121573e+07,0.85370
15,2016-4Q,85.309998,0.75,156484,330314,1680,43036,0.473743,0.005086,0.039037,214.875,361.202530,-88570.0,0.6,4.766667,1.024707e+07,0.99790
16,2017-1Q,81.480003,0.75,160438,344209,4010,58671,0.466106,0.011650,0.068347,237.900,344.986334,-70511.0,0.6,4.566667,1.294463e+07,1.14960
17,2017-2Q,81.910004,0.77,157174,343012,3350,58077,0.458217,0.009766,0.057682,255.750,346.806956,-106964.0,0.4,4.400000,1.131815e+07,1.29920
18,2017-3Q,78.970001,0.77,160229,349427,3970,61100,0.458548,0.011361,0.064975,273.600,334.358985,-98699.0,0.7,4.300000,1.021208e+07,1.33390
19,2017-4Q,82.940002,0.77,154191,348691,8380,66515,0.442200,0.024033,0.125987,291.450,351.167970,-89087.0,1.0,4.133333,9.333548e+06,1.69428
20,2018-1Q,75.779999,0.77,153915,348826,4650,68211,0.441237,0.013330,0.068171,309.300,320.852515,-78779.0,0.9,4.033333,1.585693e+07,2.31175
21,2018-2Q,81.279999,0.82,155257,348790,3950,73501,0.445130,0.011325,0.053741,373.350,344.139515,-99624.0,0.7,3.933333,1.315388e+07,2.33575
22,2018-3Q,79.419998,0.82,157797,354628,6240,76605,0.444965,0.017596,0.081457,437.400,336.264272,-139159.0,0.5,3.766667,1.034541e+07,2.39838
23,2018-4Q,80.870003,0.82,147668,346196,6000,71895,0.426545,0.017331,0.083455,501.450,342.403592,-132138.0,0.3,3.833333,1.566833e+07,2.80763
24,2019-1Q,73.980003,0.82,158168,356189,2350,63625,0.444056,0.006598,0.036935,565.500,313.231334,-106218.0,0.7,3.866667,1.289754e+07,2.59975
25,2019-2Q,76.559998,0.87,162264,360729,3130,69091,0.449822,0.008677,0.045303,607.150,324.155030,-131984.0,0.4,3.666667,1.092303e+07,2.31988
26,2019-3Q,69.629997,0.87,162252,359361,3170,65049,0.451501,0.008821,0.048732,648.800,294.813408,-140241.0,0.6,3.600000,1.062713e+07,2.08513
27,2019-4Q,70.769997,0.87,163659,362597,5690,67173,0.451352,0.015692,0.084707,690.450,299.640166,-101785.0,0.6,3.600000,1.213925e+07,1.90838
28,2020-1Q,59.959999,0.87,167061,355804,-610,56158,0.469531,-0.001714,-0.010862,732.100,253.870636,-97938.0,-1.3,3.800000,3.186602e+07,1.45050

In [74]:
pd.DataFrame(Q_scale).iloc[:,1:]

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,0.000000,0.773773,0.288852,1.000000,0.944390,0.897341,1.000000,0.720031,0.000000,0.673732,0.940885,0.814815,1.000000,0.150703,0.020178
1,0.200000,0.915677,0.350060,0.738872,0.920968,1.000000,0.734219,0.549330,0.013430,0.739938,0.670162,0.518519,0.951613,0.186514,0.016492
2,0.200000,1.000000,0.534337,0.838773,1.000000,0.963539,0.820532,0.591145,0.026860,0.732555,0.514280,0.777778,0.879032,0.104756,0.007082
3,0.200000,0.763576,0.510919,0.886251,0.979058,0.744815,0.868819,0.629764,0.040291,0.762086,1.000000,0.777778,0.806452,0.145683,0.006015
4,0.200000,0.920387,0.703745,0.960435,0.916245,0.778397,0.926083,0.704784,0.053721,0.710646,0.960660,0.370370,0.741935,0.144058,0.000000
5,0.400000,0.933205,0.875755,0.928783,0.983878,0.685797,0.882574,0.656296,0.061021,1.000000,0.674053,1.000000,0.629032,0.022293,0.000039
6,0.400000,0.720821,0.695412,0.858556,0.927395,0.589467,0.828387,0.629828,0.068320,0.923315,0.463728,0.925926,0.596774,0.008480,0.001746
7,0.400000,0.850233,0.594090,0.710188,0.652405,0.778119,0.691018,0.629458,0.075620,0.872351,0.595150,0.703704,0.508065,0.245161,0.009701
8,0.400000,0.730895,0.391754,0.548961,0.380130,0.787703,0.542976,0.613229,0.082920,0.751131,0.776176,0.814815,0.467742,0.264833,0.015599
9,0.533333,0.884348,0.555896,0.474777,0.470090,0.835700,0.463046,0.492496,0.104429,0.638724,0.520430,0.740741,0.443548,0.070784,0.020411
10,0.533333,0.661602,0.320540,0.479723,0.376335,0.763678,0.477030,0.539446,0.125939,0.417480,0.240127,0.629630,0.362903,0.266091,0.036631
11,0.533333,0.502908,0.199610,0.335312,0.000000,0.680332,0.335843,0.585046,0.147449,0.523696,0.605400,0.555556,0.346774,0.241914,0.148271
12,0.533333,0.680768,0.386426,0.239367,0.118201,0.740934,0.235626,0.350921,0.168958,0.479162,0.678962,0.703704,0.314516,0.375109,0.154441
13,0.600000,0.734294,0.376638,0.228487,0.242676,0.800770,0.224971,0.294690,0.201595,0.687068,0.542436,0.592593,0.322581,0.065930,0.164336
14,0.600000,0.602343,0.281015,0.322453,0.256292,0.729175,0.320787,0.409391,0.234231,0.629912,0.374324,0.666667,0.314516,0.083532,0.241790
15,0.600000,0.361045,0.000000,0.226508,0.039654,0.663175,0.229086,0.364631,0.266867,0.603715,0.720575,0.703704,0.282258,0.040543,0.297746
16,0.600000,0.522975,0.430412,0.456973,0.256209,0.555872,0.450200,0.578810,0.299504,0.512503,0.972416,0.703704,0.233871,0.160261,0.356612
17,0.666667,0.389303,0.393334,0.391691,0.247981,0.445024,0.386752,0.500876,0.324805,0.522744,0.464063,0.629630,0.193548,0.088078,0.414663
18,0.666667,0.514416,0.592045,0.453017,0.289852,0.449670,0.440483,0.554171,0.350106,0.452727,0.579322,0.740741,0.169355,0.038990,0.428129
19,0.666667,0.267139,0.569247,0.889219,0.364853,0.219964,0.867337,1.000000,0.375408,0.547273,0.713365,0.851852,0.129032,0.000000,0.567972
20,0.666667,0.255836,0.573429,0.520277,0.388343,0.206443,0.506812,0.577521,0.400709,0.376756,0.857115,0.814815,0.104839,0.289510,0.807577
21,0.833333,0.310795,0.572314,0.451039,0.461613,0.261144,0.439251,0.472075,0.491495,0.507740,0.566422,0.740741,0.080645,0.169548,0.816890
22,0.833333,0.414817,0.753152,0.677547,0.504605,0.258819,0.650501,0.674606,0.582282,0.463444,0.015089,0.666667,0.040323,0.044907,0.841193
23,0.833333,0.000000,0.491962,0.653808,0.439369,0.000000,0.641585,0.689208,0.673069,0.497976,0.113000,0.592593,0.056452,0.281140,1.000000
24,0.833333,0.430011,0.801505,0.292779,0.324824,0.246054,0.280006,0.349271,0.763855,0.333889,0.474466,0.740741,0.064516,0.158171,0.919333
25,1.000000,0.597756,0.942137,0.369931,0.400532,0.327072,0.350049,0.410415,0.822892,0.395332,0.115148,0.629630,0.016129,0.070542,0.810732
26,1.000000,0.597264,0.899761,0.373887,0.344548,0.350662,0.354911,0.435478,0.881928,0.230293,0.000000,0.703704,0.000000,0.057410,0.719638
27,1.000000,0.654886,1.000000,0.623145,0.373966,0.348568,0.586377,0.698354,0.940964,0.257442,0.536286,0.703704,0.000000,0.124518,0.651052
28,1.000000,0.794209,0.789580,0.000000,0.221402,0.603991,0.000000,0.000000,1.000000,0.000000,0.589934,0.000000,0.048387,1.000000,0.473374

In [76]:
Q_pca = PCA(n_components=15)
Q_pca.fit_transform(pd.DataFrame(Q_scale).iloc[:,1:])
print(Q_pca.explained_variance_ratio_)

[5.73373038e-01 1.86847629e-01 9.90758429e-02 5.90067282e-02
 3.26358218e-02 1.91751771e-02 1.23636243e-02 8.19047307e-03
 4.28356763e-03 2.74411523e-03 1.62904712e-03 5.29329523e-04
 1.38809875e-04 5.08359502e-06 1.71290281e-06]

n을 몇개로 할지, X, Y 취합가능

In [81]:
5.73 + 1.86 + 0.99

8.58

## 누적 설명률 80% 이상 기준
day data n=2  
Q data n=3

In [83]:
pca = PCA(n_components=2)
X = pca.fit_transform(X)
print(pca.explained_variance_ratio_)

[0.66234716 0.14585519]

In [92]:
day = pd.concat([pd.DataFrame(X),Y],axis=1)

In [93]:
day.columns=['X1','X2', 'Y']

In [96]:
day.to_csv('day_input.csv',index=False)

In [97]:
Q_pca = PCA(n_components=3)
X = Q_pca.fit_transform(pd.DataFrame(Q_scale).iloc[:,1:])
print(Q_pca.explained_variance_ratio_)

[0.57337304 0.18684763 0.09907584]

In [110]:
Y = pd.DataFrame(Q_scale).iloc[:,0]

In [112]:
Q = pd.concat([pd.DataFrame(X),Y],axis=1)

In [113]:
Q.columns = ['X1','X2','X3', 'Y']

In [115]:
Q.to_csv('Q_input.csv',index = False)